---
# - name: Check if Git credentials are parsed
#   ansible.builtin.debug:
#     msg: "ANSIBLE_NET_PASSWORD: {{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
#   delegate_to: localhost

- name: Clone the Git repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ root_dir }}/{{ repo_dir }}"
    version: main
    force: yes
  run_once: true
  delegate_to: localhost
  ignore_errors: true

- name: Ensure file is present in the local repo
  ansible.builtin.file:
    path: "{{ root_dir }}/{{ repo_dir }}/{{ git_repo_vendor_dir }}/{{ config_backup_file }}"
    state: touch
  delegate_to: localhost
  ignore_errors: true

# Ensures all the devices configs are included, not just one because of run_once.
- name: Add local temp config store file to local git repo
  ansible.builtin.copy:
    src: "{{ tmp_config_store }}"
    dest: "{{ root_dir }}/{{ repo_dir }}/{{ git_repo_vendor_dir }}/{{ config_backup_file }}"
  delegate_to: localhost
  register: gitlab_upload
  ignore_errors: true

# This is a one time action even if the number of devices are many.
# All updates would have been done in the prior task
- name: Commit the changes and push to the remote repository
  ansible.builtin.shell: |
     cd {{ root_dir }}/{{ repo_dir }}
     git config --global user.name {{ git_user }}
     git config --global user.email {{ git_user_email }}
     git add .
     git commit -m "Updated running-configs on $(date)"
     git push
  run_once: true
  delegate_to: localhost
  ignore_errors: true

