---
# tasks file for gitlab
- name: Import gitlab tasks
  ansible.builtin.import_tasks: gitlab.yml
  when: normal_file == true

- name: Import gitlab-lfs tasks
  ansible.builtin.import_tasks: gitlab-lfs.yml
  when: large_file == true